### ISSUE TITLE
Do you have the detailed category-wise AP score of VOC of RFBNet?

### ISSUE THREAD

**Issue by qijiezhao** [ShuangXieIrene/ssds.pytorch#1]
Hi, glad to see your amazing work, and I am also interested in reconsidering SSD-stream methods.

Can you have a share of the result of detailed category-wise AP score of VOC07 of RFBNet, which is missing at the author's arxiv paper.

**Comment by foreverYoungGitHub** [comment]
You mean the rfbnet with vgg16? Actually, that is the only model I do not trained by myself. I grab it from RFBNet repo. You can test it directly by download the model and test it by changing the relative cfg file.

I can also test it later, but the gpu is still training now.

**Comment by foreverYoungGitHub** [comment]
This is the value I tested:

```
AP for aeroplane = 0.8410
AP for bicycle = 0.8531
AP for bird = 0.7780
AP for boat = 0.7375
AP for bottle = 0.5646
AP for bus = 0.8857
AP for car = 0.8697
AP for cat = 0.8790
AP for chair = 0.6469
AP for cow = 0.8456
AP for diningtable = 0.7716
AP for dog = 0.8561
AP for horse = 0.8750
AP for motorbike = 0.8563
AP for person = 0.8108
AP for pottedplant = 0.5624
AP for sheep = 0.8016
AP for sofa = 0.8064
AP for train = 0.8833
AP for tvmonitor = 0.7887
Mean AP = 0.7957
```
