### ISSUE TITLE
failed when run : python demo.py --cfg=$file --demo=./experiments/person.jpg

### ISSUE THREAD

**Issue by liwei46** [ShuangXieIrene/ssds.pytorch#14]
./experiments/cfgs/ssd_lite_mobilenetv2_train_voc.yml
===> Building model
==>Feature map size:
[(19, 19), (10, 10), (5, 5), (3, 3), (2, 2), (1, 1)]
Utilize GPUs for computation
Number of GPU available 1
=> loading checkpoint ./weights/ssd_lite/mobilenet_v2_ssd_lite_voc_73.2.pth
/home/wei_li/anaconda3/lib/python3.6/site-packages/torch/tensor.py:321: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return self.mul(other)
ASSERT: "false" in file qasciikey.cpp, line 501
./time_benchmark.sh: line 9: 16177 Aborted                 (core dumped) python demo.py --cfg=$file --demo=./experiments/person.jpg

**Comment by foreverYoungGitHub** [comment]
Which pytorch version are you using now. Currently, it only support 0.3.1. It will support 0.4.0 later.

**Comment by liwei46** [comment]
Thanks for the reply. I am using 0.3.1, maybe due to my GPU memory not enough... sometimes it works. I will close it.

**Comment by rawandeheliah** [comment]
i have the same problem ? 
when i run a python file uses opencv , how did you fix this problem ?
