### ISSUE TITLE
demo.py issue

### ISSUE THREAD

**Issue by kaishijeng** [ShuangXieIrene/ssds.pytorch#15]
Encounter an error when running demo.py below:
python3 ./demo.py --cfg=./experiments/cfgs/fssd_lite_mobilenetv1_train_voc.yml --demo=./experiments/person.jpg

===> Building model
/home/topspin/2TB/src/ssds.pytorch/lib/modeling/model_builder.py:51: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x = torch.autograd.Variable(x, volatile=True) #.cuda()
/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py:1761: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
==>Feature map size:
[(38, 38), (19, 19), (10, 10), (5, 5), (3, 3), (1, 1)]
/home/topspin/2TB/src/ssds.pytorch/lib/ssds.py:21: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors = Variable(self.priorbox.forward(), volatile=True)
Utilize GPUs for computation
Number of GPU available 1
=> loading checkpoint ./weights/fssd_lite/mobilenet_v1_fssd_lite_voc_78.4.pth
/home/topspin/2TB/src/ssds.pytorch/lib/ssds.py:68: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x = Variable(self.preprocessor(img)[0].unsqueeze(0),volatile=True)
Traceback (most recent call last):
  File "./demo.py", line 154, in <module>
    demo(args, args.demo_file)
  File "./demo.py", line 59, in demo
    _labels, _scores, _coords = object_detector.predict(image)
  File "/home/topspin/2TB/src/ssds.pytorch/lib/ssds.py", line 82, in predict
    detections = self.detector.forward(out)
  File "/home/topspin/2TB/src/ssds.pytorch/lib/layers/functions/detection.py", line 151, in forward
    ids, count = nms(boxes, scores, self.nms_thresh, self.top_k)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by foreverYoungGitHub** [comment]
I think you are using pytorch 0.4.0. currently the code is suitable for 0.3.1. It'll update to 0.4.0 in few weeks.

**Comment by kaishijeng** [comment]
Yes, it is due to 0.4.0

Thanks,

**Comment by XiaSunny** [comment]
您好，请问下，你这个文件：mobilenet_v1_fssd_lite_voc_78.4.pth是怎么得到的？我的weight路径下什么都没有呀

**Comment by kamauz** [comment]
I've tried to use PyTorch 0.3.1 but now the problem is on the GPU that is not supported :laughing:
