### ISSUE TITLE
No module named 'lib.utils.nms._ext.nms._nms'

### ISSUE THREAD

**Issue by wwdguu** [ShuangXieIrene/ssds.pytorch#2]
When I try to run the demo, I get the following error:
 from ._nms import lib as _lib, ffi as _ffi
ImportError: No module named 'lib.utils.nms._ext.nms._nms'

Ubuntu 16.04.3
GTX 1080Ti
Cuda 8.0 installed

**Comment by foreverYoungGitHub** [comment]
Currently there are two nms exists in the code. One is implemented by pytorch, the other is implemented. For the easier usage. I'll change all the nms to pytorch version. But if you want to use the cuda version, you need to compile the code based on [this](https://github.com/ShuangXieIrene/ssds.pytorch/tree/master/lib/utils/nms/make.sh) . The original version is compiled by Ubuntu 16.04.3, Cuda 9.0.

Besides, my personal suggest is that, the new cuda version have good improvement in speed.
