### ISSUE TITLE
how to train from scratch

### ISSUE THREAD

**Issue by 1Konny** [ShuangXieIrene/ssds.pytorch#20]
Hi. 

can you tell me what is the proper way to train object detector from scratch with pretrained base architectures such as Resnet50, VGG16, MobilenetV1, MobilenetV2?
or can you give me some references regarding this?

I first tried by command line below but it seemed that the training starts without pretrained weights. 
`python train.py --cfg=./experiments/cfgs/ssd_vgg16_train_voc.yml`

So now I'm training VGG16-SSD on voc dataset using exactly the same command below
`python train.py --cfg=./experiments/cfgs/ssd_vgg16_train_voc.yml`
but changed `RESUME_CHECKPOINT` and `PHASE` like this
RESUME_CHECKPOINT: './weights/ssd/vgg16_reducedfc.pth' 
PHASE: ['train']
and also I downloaded `vgg16_reducedfc.pth` from https://s3.amazonaws.com/amdegroot-models/vgg16_reducedfc.pth and put into `./weights/ssd/`
but I wonder it is the right way to do it.

by the way, thanks for your great project! It seems like well-written, understandable codes! It helps me a lot.

**Comment by bailvwangzi** [comment]
how did you train with pretrained model?thanks
