### ISSUE TITLE
  ASPECT_RATIOS

### ISSUE THREAD

**Issue by isalirezag** [ShuangXieIrene/ssds.pytorch#23]
Whay the aspect ratios are define like this:

ASPECT_RATIOS: [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2], [1, 2]]
 can any body explain it please?

Also i see in another place it also define like:

ASPECT_RATIOS: [[[0.1,0.1], [0.2,0.2], [0.3,0.3], [0.5,0.5], [0.9,0.9]]]

I am not sure why? plus should not aspect ratio be like 1:2 ....

**Comment by foreverYoungGitHub** [comment]
just 2 way to initialize the aspect ratio. Please check the [code](https://github.com/ShuangXieIrene/ssds.pytorch/blob/1233516ad99c95dfb4b5cf1b29a2ced1b8351170/lib/layers/functions/prior_box.py#L46).
