### ISSUE TITLE
_mask doesn't get imported

### ISSUE THREAD

**Issue by vaishnavm217** [ShuangXieIrene/ssds.pytorch#27]
The `_mask` is not getting imported.
its present in pycoco. the previous [issue](https://github.com/ShuangXieIrene/ssds.pytorch/issues/22) solved it using python3,but I am facing the same using python3. I think the issue is that this file is capable only with python 3.6 not 3.5. ( as the name itself is `_mask.cpython-36m-x86_64-linux-gnu.so`)

**Comment by Maphist0** [comment]
I also had this problem. It seems that upgrading python from 3.5 to 3.6 would solve it. 
(I use anaconda. Upgrade by `conda update python`, [ref](https://conda.io/docs/user-guide/tasks/manage-python.html#updating-or-upgrading-python).)

**Comment by vaishnavm217** [comment]
@Maphist0  mentioned solution is the best. Or else if you are not using coco api and coco eval (custom dataset), you can just comment coco dependencies from` dataset_factory` like I did.

**Comment by cardoso-neto** [comment]
To anyone reading this: my solution was to run `pip install pycocotools` and change the imports accordingly.
