### ISSUE TITLE
Where to download the pre-trained MobileNetv2 model?

### ISSUE THREAD

**Issue by JesseYang** [ShuangXieIrene/ssds.pytorch#3]
I want to train ssd_lite with MobileNetv2 as the backbone. The pre-trained MobileNetv2 model should b loaded. Where can I download the pre-trained model? Thanks

**Comment by ShuangXieIrene** [comment]
Please download from the hyper-link in readme Performance section :)

**Comment by JesseYang** [comment]
Thanks. But those links refer to the SSD models, which can be used to do inference or evaluate the performance. When training the model by myself, MobileNetv2 model pre-trained on ImageNet should be loaded.

**Comment by foreverYoungGitHub** [comment]
You can try this one: https://github.com/tonylins/pytorch-mobilenet-v2
