### ISSUE TITLE
multi gpu training 

### ISSUE THREAD

**Issue by wwdguu** [ShuangXieIrene/ssds.pytorch#5]
Hi, I  am trying to train the  ssds network with multi gpu , but it seems doesn't working. I just use the DataParallel class. Are there any tricks to implent this? Thanks a lot.

**Comment by xiaollz** [comment]
May I ask you how did you manage to do that?
Thx!

**Comment by isalirezag** [comment]
Can you please tell us how to do it, i can uncomment DataParallel in the code and run the code via DataParallel
but it still uses one gpu
