### ISSUE TITLE
_expand function in data_augment.py

### ISSUE THREAD

**Issue by dhananjaisharma10** [ShuangXieIrene/ssds.pytorch#62]
Hi!

I was going through the `data_augment.py` file which uses the `_expand` function. It enlarges the image where all the pixels are equal to the mean of the images in the dataset and then equates a portion of this bigger image to the original image. Can someone explain the significance of this technique?

Thanks!

**Comment by foreverYoungGitHub** [comment]
Cause the first step in preprocess in minus the mean value to the original image, that is the reason why setting the background to mean value. The second part is doing the data argumentation to achieve the better performance in different scale of image.
