### ISSUE TITLE
下载预训练pth预测时模型不匹配

### ISSUE THREAD

**Issue by dream-in-night** [ShuangXieIrene/ssds.pytorch#63]
当使用训练好的pth文件进行预测时，出现以下问题：
`self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RFBLite:
	size mismatch for base.14.conv.6.weight: copying a param with shape torch.Size([160, 576, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 576, 1, 1]).
`
为什么作者训练的模型与源码中的模型不匹配呢？
然而我自己训练了300次后，rfb_lite和ssd_lite mobilenetV2都只有60左右的准确率。
还有，整个train.txt中显示的最少的也有2500个图片数量，但是训练时，每个epoch只有518个图片(data_factory.py文件中loaddata回调)，这样是否会对精度造成影响？
期待回复

**Comment by foreverYoungGitHub** [comment]
I'm not so sure why the number of image is 518 in the dataset, maybe that is the number of the iteration per epoch? Would you mind sharing your log for that part? Also I've touch the code for nearly 1 year. some part may not suitable for the newest version of pytorch. I'll reconstruct all the code recently, please check dev branch for the newest updated code.
