### ISSUE TITLE
how to slove this  -----   no model named '_mask'

### ISSUE THREAD

**Issue by DENESTY** [ShuangXieIrene/ssds.pytorch#73]

**Comment by LoveMartina** [comment]
If your dataset is VOC, you just delete the code of COCO.

**Comment by foreverYoungGitHub** [comment]
_mask is from the cpp binary file in pycoco lib code. But if you install the library shown in dev branch, this problem should not be existed.

since the problem should be fixed in the newer version of code, will close this issue for now.
