### ISSUE TITLE
run in jetson nano raise error... RuntimeError:cuda runtime error(7):too many resources requested for launch at..........how to solve it

### ISSUE THREAD

**Issue by DENESTY** [ShuangXieIrene/ssds.pytorch#77]

**Comment by QZ-cmd** [comment]
jetson nano can‘t train model

**Comment by DENESTY** [comment]
@QZ-cmd
The model was trained on the x86 computer，Errors occur in inference on jetson nano

**Comment by foreverYoungGitHub** [comment]
I do not have the jetson nano to test the model, but I can use jetson tx2 to run the trt model converted from ssds.pytorch. Did you try to convert the model to trt?

**Comment by foreverYoungGitHub** [comment]
@DENESTY Just tested the converted trt model on the Jetson tx2 today, and everything works fine. If you need I can share how to convert the model from ssds.pytorch to tensorrt.

Since the issues is not existed on the trt model on the Jetson tx2. I'll close the issue for now.
